inf1407/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls.base import reverse_lazy

from conta.views import (
    tela_inicial_view,
    registro_view,
    logout_view,
    login_view,
    atualiza_view,
    precisa_autenticar_view,
    verifica_titulo,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', tela_inicial_view, name="tela-inicial"),
    path('postagens/', include('postagens.urls', 'postagens')),
    path('registro/', registro_view, name="tela-registro"),
    path('logout/', logout_view, name="tela-logout"),
    path('login/', login_view, name="tela-login"),
    path('atualiza/', atualiza_view, name="tela-atualiza"),
    path('precisa-autenticar/', precisa_autenticar_view, name="tela-precisa-autenticar"),
    path('verificaTitulo/', verifica_titulo,name='verificaTitulo'),

    #links de redefinição de senha padrão do Django
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="registration/password_change_done.html"),
        name="password_change_done"),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name="registration/password_change.html"),
        name="password_change"),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="registration/password_reset_done.html"),
        name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="registration/password_change.html",
        success_url=reverse_lazy('password_reset_complete'),),  
        name="password_reset_confirm"),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
        name="password_reset"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="registration/password_reset_complete.html"),
        name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postagens/urls.py
from django.urls import path
from postagens.views import (
    cria_post_view,
    detalhes_post_view,
    edita_post_view,
    deleta_post_view,
    deletar_post_view,
    verifica_titulo,
)

app_name= 'postagens'

urlpatterns = [
    path('cria/', cria_post_view, name="cria"),
    path('<slug>/', detalhes_post_view, name="detalhe"),
    path('<slug>/edit/', edita_post_view, name="edita"),
    path('<slug>/delete', deleta_post_view, name="apaga"),
    path('<slug>/deleted', deletar_post_view, name="apagar"),
    path('<slug>/verificaTitulo/', verifica_titulo,name='verificaTitulo'),
]

postagens/models.py
from django.db import models

from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

def caminho_upload(instance, filename, **kwargs):
    file_path = 'blog/{autor_id}/{titulo}-{filename}'.format(
       autor_id = str(instance.autor.id), titulo=str(instance.titulo), filename=filename
    )
    return file_path

class Postagem(models.Model):
    titulo = models.CharField(max_length=50, null=False, blank=False)
    corpo = models.TextField(max_length=5000, null=False, blank=False)
    imagem = models.ImageField(upload_to=caminho_upload, blank=False)
    data_publicacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de Publicação")
    data_atualizacao = models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #slug cria uma URL automaticamente para as postagens
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.titulo

@receiver(post_delete, sender=Postagem)
def delete_submissao(sender, instance, *args, **kwargs):
    instance.imagem.delete(False)

def pre_salvar_postagem_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.autor.username + "-" + instance.titulo)

pre_save.connect(pre_salvar_postagem_receiver, sender=Postagem)

postagens/forms.py
from django import forms

from postagens.models import Postagem

class CriaFormularioDaPostagem(forms.ModelForm):

    class Meta:
        model = Postagem
        fields = ['titulo', 'corpo', 'imagem']


class AtualizaFormPostagem(forms.ModelForm):

    class Meta:
        model = Postagem
        fields = ['titulo', 'corpo', 'imagem']

    def save(self, commit=True):
        postagem_blog = self.instance
        postagem_blog.titulo = self.cleaned_data['titulo']
        postagem_blog.corpo = self.cleaned_data['corpo']

        if self.cleaned_data['imagem']:
            postagem_blog.imagem = self.cleaned_data['imagem']

        if commit:
            postagem_blog.save()
        return postagem_blog

class DeletaFormPostagem(forms.ModelForm):
    class Meta:
        model = Postagem
        fields = ['titulo', 'corpo', 'imagem']

    def delete(self, commit=True):
        postagem_blog = self.instance
        postagem_blog.titulo = self.cleaned_data[None]
        postagem_blog.corpo = self.cleaned_data[None]
        postagem_blog.imagem = self.cleaned_data[None]
        return postagem_blog

postagens/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from postagens.models import Postagem
from postagens.forms import CriaFormularioDaPostagem
from postagens.forms import AtualizaFormPostagem
from conta.models import Conta
from django.http import JsonResponse

#postagem_blog.titulo
def cria_post_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("tela-precisa-autenticar")
    
    form = CriaFormularioDaPostagem(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        autor = Conta.objects.filter(email=user.email).first()
        obj.autor = autor
        obj.save()
        form = CriaFormularioDaPostagem()

    context['form'] = form

    return render(request, "postagens/cria-post.html", context)

def detalhes_post_view(request, slug):
    context = {}

    postagem_blog = get_object_or_404(Postagem, slug=slug)
    context['postagem_blog'] = postagem_blog

    return render(request, 'postagens/detalhes-post.html', context)

def edita_post_view(request, slug):
    
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("tela-precisa-autenticar")

    postagem_blog = get_object_or_404(Postagem, slug=slug)
    if postagem_blog.autor != user:
        return HttpResponse('Você não é o autor desta postagem.')
    
    if request.POST:
        form = AtualizaFormPostagem(request.POST or None, 
            request.FILES or None, instance=postagem_blog)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Atualizado!"
            postagem_blog = obj

    form = AtualizaFormPostagem(
        initial = {
            "titulo": postagem_blog.titulo,
            "corpo": postagem_blog.corpo,
            "imagem": postagem_blog.imagem,
        }
    )

    context['form'] = form
    return render(request, 'postagens/edita-post.html', context)

def deleta_post_view(request, slug):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect("tela-precisa-autenticar")
    postagem_blog = get_object_or_404(Postagem, slug=slug)
    if postagem_blog.autor != user:
        return HttpResponse('Você não é o autor desta postagem.')
    
    context['postagem_blog'] = postagem_blog
    return render(request, 'postagens/apaga-get.html', context)

def deletar_post_view(request, slug):
    context = {}
    user = request.user
    postagem_blog = get_object_or_404(Postagem, slug=slug)
    postagem_blog.delete()
    return render(request, 'postagens/apaga-post.html', context)

def verifica_titulo(request, slug):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect("tela-precisa-autenticar")
    postagem_blog = get_object_or_404(Postagem, slug=slug)
    if postagem_blog.autor != user:
        return HttpResponse('Você não é o autor desta postagem.')

    
    titulo = request.GET.get("id_title", None)
    resposta = {
        'existe':
            Postagem.objects.filter(id_title__iexact=titulo).exists()
    }
    return JsonResponse(resposta)

postagens/templates/postagens/apaga-get.html
{% extends 'base.html' %} {% block content %}

<style type="text/css">
    .card {
        max-width: 700px;
    }
    
    .container {
        padding: 20px;
    }
</style>

<div class="container">
    <div class="row">
        <!-- Postagem do Blog -->
        <div class="card m-auto">
            <img class="card-img-top" src="{{postagem_blog.imagem.url}}">
            <div class="card-body my-2">
                <h2 class="card-title">{{postagem_blog.titulo}}</h2>
                <p class="card-text">{{postagem_blog.corpo|safe}}</p>
                {% if postagem_blog.autor == request.user %}
                <a href="{% url 'postagens:apagar' postagem_blog.slug %}" class="btn btn-primary">Apagar</a> {% endif %}
            </div>
            <div class="card-footer text-muted">
                Atualizado em {{postagem_blog.data_atualizacao}} por {{postagem_blog.autor}}
            </div>
        </div>
        <!-- end Postagem do Blog -->
    </div>
</div>

{% endblock content %}

postagens/templates/postagens/apaga-post.html
{% extends 'base.html' %} {% block content %}

<style type="text/css">
    .card {
        max-width: 700px;
    }
    
    .container {
        padding: 20px;
    }
</style>

<div class="container">
    <div class="row">
        <!-- Postagem do Blog -->
        <div class="card m-auto">
            <div class="card-body my-2">
                <p>Postagem apagada com sucesso.</p>
            </div>
            <div class="card-footer text-muted">
                Atualizado em {{postagem_blog.data_atualizacao}} por {{postagem_blog.autor}}
            </div>
        </div>
        <!-- end Postagem do Blog -->
    </div>
</div>

{% endblock content %}

postagens/templates/postagens/cria-post.html
{% extends 'base.html' %} {% load static %} {% block content %}

<style type="text/css">
    .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
    }
    
    .submit-button {
        max-width: 200px;
    }
</style>
<script type="text/javascript">
    onload = function() {
        document.getElementById('id_title').addEventListener('keyup', function(e) {
            // recupera o campo usern ame do formu lário
            var titulo = document.getElementById('id_title');
            console.log(' Mudou ', titulo.value);
            // cria o obj eto HTTP Req uest
            var xmlhttp = new XMLHttpRequest();
            // Abre a con exão
            xmlhttp.open("GET", "{% url 'verificaTitulo' %}?titulo=" +
                encodeURIComponent(titulo.value), true);
            // Função de callback
            xmlhttp.onreadystatechange = function() {
                if (xmlhttp.status == 200 && xmlhttp.readyState == 4) {
                    var resposta = JSON.parse(xmlhttp.responseText);
                    console.log("Resposta = " + resposta.existe);
                    if (resposta.existe) {
                        titulo.style = "border: 4px solid #FF0000";
                        document.getElementById('idMsgErro').replaceChild(
                            document.createTextNode("Titulo já existe"),
                            document.getElementById('idMsgErro').firstChild);
                    } else {
                        titulo.style = "border: 4px solid #00FF00";
                        document.getElementById('idMsgErro').replaceChild(
                            document.createTextNode("OK"),
                            document.getElementById('idMsgErro').firstChild);
                    }
                }
            };
            // Envia o Request
            xmlhttp.send(null);
        });
    }
</script>
<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Título</label>
                    <input class="form-control" type="text" name="titulo" id="id_title" placeholder="Título" required autofocus>
                </div>

                <!-- Body -->
                <div class="form-group">
                    <label for="id_body">Conteúdo</label>
                    <textarea class="form-control" rows="10" type="text" name="corpo" id="id_body" placeholder="Esta postagem é sobre..." required></textarea>
                </div>

                <!-- Image -->
                <div class="form-group">
                    <label for="id_image">Imagem</label>
                    <input type="file" name="imagem" id="id_image" accept="image/*" required>
                </div>

                <!-- Submit btn -->
                <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POSTAR!</button>
            </form>
        </div>
    </div>
</div>




{% endblock content %}

postagens/templates/postagens/detalhes-post.html
{% extends 'base.html' %}

{% block content %}

    <style type="text/css">
        .card{
            max-width: 700px;
        }

        .container{
            padding: 20px;
        }
    </style>

    <div class="container">
        <div class="row">
            <!-- Postagem do Blog -->
            <div class="card m-auto">
                <img class="card-img-top" src="{{postagem_blog.imagem.url}}">
                <div class="card-body my-2">
                    <h2 class="card-title">{{postagem_blog.titulo}}</h2>
                    <p class="card-text">{{postagem_blog.corpo|safe}}</p>
                    {% if postagem_blog.autor == request.user %}
                        <a href="{% url 'postagens:edita' postagem_blog.slug %}" class="btn btn-primary">Atualizar</a>
                    {% endif %}
                </div>
                <div class="card-footer text-muted">
                    Atualizado em {{postagem_blog.data_atualizacao}} por {{postagem_blog.autor}}
                </div>
            </div>
            <!-- end Postagem do Blog -->
        </div>
    </div>

{% endblock content %}

postagens/templates/postagens/edita-post.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- título -->
				<div class="form-group">
					<label for="id_title">Título</label>
					<input class="form-control" type="text" name="titulo" id="id_title" placeholder="Título" value="{{form.initial.titulo}}" required autofocus>
				</div>

				<!-- corpo -->
				<div class="form-group">
					<label for="id_body">Conteúdo</label>
					<textarea class="form-control" rows="10" type="text" name="corpo" id="id_body" placeholder="Esta postagem é sobre..." 
					required>{{form.initial.corpo}}</textarea>
				</div>

				<!-- imagem -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.imagem.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Muda imagem</div>
					  </div>
				</div>
				<input type="file" name="imagem" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Atualiza Postagem</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}